### PR TITLE
Fix issue #11

### LINKED ISSUE #11: Potential thread safety issue during initialisation of plugin
**Snap version** (use `snapctl -v`): ANY
**Environment**:
- **Cloud provider or hardware configuration**: ANY
- **OS** (e.g. from /etc/os-release): Linux (Debian 8.0 & Ubuntu 1[46].04 amd64)

Potential thread safety issue during initialisation of plugin

Looking at a [PR which has been integrated earlier for the SMART plugin](https://github.com/intelsdi-x/snap-plugin-collector-smart/pull/18/commits), and more specifically at [commit bf7c332](https://github.com/intelsdi-x/snap-plugin-collector-smart/pull/18/commits/bf7c3327f0d4cae8d73629cb76ca46d25c8c7985) and [commit dada577](https://github.com/intelsdi-x/snap-plugin-collector-smart/pull/18/commits/dada577cda22547aae0d1dc3968e6401cb580292) which have been added to comply with @lmroz [comment r73497782] (https://github.com/intelsdi-x/snap-plugin-collector-smart/pull/18#r73497782), the same code should be integrated into swap collector plugin

### PR DESCRIPTION
**Pull request by obourdon**
Fixes #11 

Summary of changes:
-  Fix issue:Potential thread safety issue during initialisation of plugin
- Added more tests for better code coverage
- Uniformize coding across plugins
- Remove dead/useless code
- Fixed typo

Testing done:
- small and legacy test suites passed successfully

### CODE REVIEW

File: swap/swap.go [hunk 1]
```diff
@@ -473,11 +481,9 @@ func getIOmetrics(swap *Swap) error {
 	oldSwapOut := swap.ioHistory.swapOut
 	oldTimestamp := swap.ioHistory.timestamp
 	duration := time.Since(oldTimestamp).Seconds()
```
Comment (jcooklin) [inline swap/swap.go]: On the **first** collection all of the per_sec calculations will have a divisor that is ~= the seconds since the empty time value.  Do the 'per sec' metrics need time to warm up?

File: swap/swap.go [hunk 2]
```diff
@@ -90,11 +99,39 @@ type ioData struct {
 
 // Meta returns plugin meta data
 func Meta() *plugin.PluginMeta {
-	return plugin.NewPluginMeta(name, version, pluginType, []string{}, []string{plugin.SnapGOBContentType})
+	return plugin.NewPluginMeta(PluginName, version, pluginType, []string{}, []string{plugin.SnapGOBContentType})
```
Comment (jcooklin) [inline swap/swap.go]: The option plugin.RoutingStrategy(plugin.StickyRouting) should be added to ensure that there is a 1:1 relationship between running tasks and running plugin instances.

Comment (obourdon) [inline swap/swap.go]: Understood and agreed. Will change this in the next PR revision

File: swap/swap.go (hunk 1 above)
Comment (obourdon) [inline swap/swap.go]: The tests I have carried out so far seems to show that time between call to [plugin init lines](https://github.com/obourdon/snap-plugin-collector-swap/blob/master/swap/swap.go#L115-L119)  and call to [duration computation for historical data](https://github.com/obourdon/snap-plugin-collector-swap/blob/master/swap/swap.go#L475) can not give a duration lower than the task schedule interval

Besides securing the code so that test on [line #477](https://github.com/obourdon/snap-plugin-collector-swap/blob/master/swap/swap.go#L477) becomes `if int(duration) == 0  {` I think we are pretty much safe here
